
;+
; NAME:
; RRCAT_READ_SPC
;
; PURPOSE: reads a Grams/32 compatable .spc file. May be some bugs
;		when reading a Grams generated file. Can read single spectra
;		or multi-spectra files.
;
;		-note that GRAMS should be set to use IEEE floating point output, since
;		there seems to be a problem reading in the non-IEEE format.
;
; CATEGORY:
;	spectra
;
; CALLING SEQUENCE:
;	RRCAT_READ_SPC,Filename,Freq,Ydata
;
; INPUTS:
;	Filename = string filename (and path if needed). If filename is null,
;		then a file selection dialog will appear.
;
; OUTPUTS:
;	Freq = wavenumber or frequency array
;	Ydata = float intensity data. If the file contains multiple spectra,
;				then the Ydata parameter will contain an [m,n] element array
;				where m is the number of frequency points, and n is the number
;				of spectra.
;
; KEYWORD PARAMETERS:
;	CATXT : set this to a named variable to contain the custom axis text string
;	COMMENT : set this to a named variable to contain the comment string
;					if it exists.
;	DEBUG: Set this keyword to print diagnostic messages
;	ERR : set this keyword to a named variable to contain any error codes.
;			In normal operation, err will be zero.
;			If no file was selected, err will be 1.
;			If file is wrong type, err will be -1
;			If file has bad header, err will be -2
;	HEADER : set this keyword to a named variable to contain the header block. Header
;			blocks are read in as named structures according to the block length. If a custom
;			header is written to a file, READ_SPC must be modified to recognize the block length
;			and load the named structure definition.
;				(This keyword is the same as the MZINFO keyword, which is provided
;				for backwards compatibility.)
;	RES : set this to a named variable to contain the resolution string
;	SOURCE : set this to a named variable to contain the source type string. 8 characters.
;	XUNITS : set this keyword to return a number indicating the frequency scale units:
;					0	Arbitrary Units
;					1	Wavenumber (cm-1)	(DEFAULT)
;					2	Wavelength (um)
;					3	Wavelength (nm)
;					6	Frequency (Hz)
;					7	Frequency (KHz)
;					8	Frequency (MHz)
;					26 Frequency (GHz)
;					255 Interferogram
;	XUNIT_TEXT: this keyword returns the frequency unit text given above
;	YUNITS : this keyword to determine the amplitude scale units:
;					0		Arbitrary Intensity	(DEFAULT)
;					1		Interferogram
;					2		Absorbance
;					5		Volts
;					9		Millivolts
;					10		Log (1/R)
;					11		Percent
;					12		Intensity
;					13		Relative Intensity
;					24		Real
;					25		Imaginary
;					26		Complex
;					128	Transmission (ALL TYPES >=128 ARE ASSUMED TO HAVE INVERTED PEAKS!)
;					129	Reflectance
;					130	Arbitrary or Single Beam with Valley Peaks
;					131	Emission
;	YUNIT_TEXT: this keyword returns the amplitude unit text given above
;	ZUNITS : this keyword returns the scale units for multi-spectra files:
;					0		Arbitrary (DEFAULT)
;	ZUNIT_TEXT: this keyword returns the amplitude unit text given above
;	ZDATA: this keyword returns the array of values for the Z axis in multi-spectra files.
;
;	----- deprecated keywords ------
;
;	INFO1,INFO2: info blocks from .sp* files. SET BOTH or NEITHER. For compatibility
;						with the old FTS software when reading new MZ FTS files, only
;						info1 is valid.
;	MZINFO : info block for the new MZ FTS. This keyword supercedes info1/info2.
;
;
;
; EXAMPLE:
;
;		read_spc,'test.spc',wn,ydata,comment=comment,res=res,$
;			source=source,catxt=catxt,header=mystructure
;		plot,wn,ydata
;
; MODIFICATION HISTORY:
; 	Written by:	BGG, 1999.
;	August, 2001	Changed to work with new MZ-FTS infoblocks
;	 NOTE : will not properly read different files generated by GRAMS/32
;		N.B. - if you set the info2 keyword, make sure you are reading
;				an old format file!!
;	Feb 2004, -added a FREQ keyword
;			  -added error handling, and an ERR keyword
;	Apr 2004  -added support for step and integrate (version 2) infoblocks
;	Oct 2005 - added support for MPI FTS files and a header keyword
;	Nov 22 2005 (BGG) - removed xstart and xinc parameters. now returns full frequency array.
;					-removed freq keyword
;	Mar 16 2006 (BGG) -fixed bug in spchdr and subhdr structures. These are now defined externally.
;	Aug 21 2006 (BGG) -fixed problem with BTRAM file header size. NOTE that the
;							structure size reported by n_tags({struct},/length) gives the total
;							size of the structure after IDL has padded the fields to the proper
;							byte boundaries, and this is platform dependant!! In Linux, the
;							size of an IDL structure is different than in Windows, even if the
;							file size is the same!
;									THERE WILL PROBABLY BE BUGS IN OLDER FORMAT DATA WRITTEN AFTER
;									THE PRESENT DATE, SINCE THE HEADER SIZE IN logstc.logbins USED TO
;									BE CALCULATED BY n_tags({struct},/length)	WHEREAS NOW,
;									WRITE_SPC uses n_tags({struct},/data_length)
;
;	Aug 22 2006 (BGG) -added error handler.
;	Mar 5 2007 (BGG) -fixed bug with 0 length headers
;	June 27 2008 (BGG) -now doesn't try and call structure definition routines if the header keyword isn't set
;	July 11 2008 (BGG) -fixed minor keyword issue. MZ info block can now be returned using the HEADER keyword.
;	Aug 20 2008 (BGG) -added err code of -2 for bad header size , updated error handling to set the !error_state
;	Sept 7 2012 (BGG) -minor updates
;	07 Mar 2018 (TRF) - modified for RRCAT header. Will integrate into main READ_SPC when RRCAT header structure
;	                    is finalized. 
;-


pro rrcat_read_spc,$
  filename,$
  freq,$
  ydata,$
  comment=comment,$
  res=fres, $
  header=header,$
  source=fsource,$
  catxt=fcatxt,$
  info1=info1,$
  info2=info2,$
  mzinfo=info, $
  debug=debug, $
  xunits=xunits, $
  yunits=yunits, $
  zunits=zunits, $
  xunit_text=xunit_text, $
  yunit_text=yunit_text, $
  zunit_text=zunit_text, $
  zdata=zdata,$
  error=err

  lun=500	;temporary lun
  err=0

  ;assume there are no errors to start with
  MESSAGE, /RESET
  ;Define the error message blocks
  name = ['WRONG_EXT', 'BAD_HEADER', 'UNHANDLED']
  fmt  = ['Wrong extension: .SPC files only!', 'Unexpected file header size: %s bytes.', 'Unhandled error: %s']
  DEFINE_MSGBLK, 'READ_SPC', name, fmt, PREFIX = 'READ_SPC_' , /ignore_duplicate

  ; Establish error handler. When errors occur, the index of the
  ; error is returned in the variable err:
  CATCH, err

  ;This statement begins the error handler:
  IF err NE 0 THEN BEGIN
    if n_elements(been_here) then return	;avoid infinite loop
    if n_elements(filename) eq 0 then filename=''
    been_here=1
    ;		result=dialog_message( $
    ;			['Unhandled error reading '+filename+'!',$
    ;			!error_state.msg],$
    ;			title='Unhandled READ_SPC Error',/center,/error)
    message, name='read_spc_unhandled', block='read_spc', !error_state.msg, /cont
    free_lun,lun	;close files just in case
    return
  ENDIF


  if n_elements(debug) eq 0 then debug=0

  if n_elements(filename) eq 0 then filename=''
  if ~file_test(filename,/read) then filename=dialog_pickfile(filter='*.spc',title='Select a .spc file to read')
  if filename eq '' then begin
    err=1
    return
  endif

  parts=str_sep(filename,'.')
  nparts=n_elements(parts)
  if nparts lt 2 then filename=filename+'.spc' else begin
    base=STRJOIN(parts[0:nparts-2], '.', /SINGLE )
    if parts[nparts-1] eq '' then filename=base+'.spc' else $
      if STRLOWCASE(parts[nparts-1]) ne 'spc' then begin
      message, name='read_spc_wrong_ext', block='read_spc',/cont
      err=-1
      return
    endif
  endelse

  ;Open the file
  openr,lun,filename,/get

  SPCHDR={SPCHDR}

  SUBHDR={SUBHDR}

  readu,lun,SPCHDR
  ;	fexp=fix(spchdr.fexp)-128   why the -128?
  fexp=fix(spchdr.fexp)

  if spchdr.fversn ne '4b'xb then message,'NOT NEW SPC FORMAT',/info

  if debug then begin
    message,'SPCHDR.FTFLAGS = '+strtrim(fix(spchdr.ftflgs),2),/info
    case 1 of
      spchdr.ftflgs eq 0: message,'Generic format',/info
      (spchdr.ftflgs AND 1) gt 0: message,'Y data blocks are 16 bit integer (only if fexp is NOT 0x80h)',/info
      (spchdr.ftflgs AND 2) gt 0: message,'Enables fexper in older software (not used)',/info
      (spchdr.ftflgs AND 4) gt 0: message,'Multifile data format (more than one subfile)',/info
      (spchdr.ftflgs AND 8) gt 0: message,'Z values in SUBHDR structures are in random order (not used)',/info
      ((spchdr.ftflgs AND 16) gt 0) && ((spchdr.ftflgs AND 4) gt 0): message,'Z values are in ascending or descending order but not evenly spaced. Z values read from individual SUBHDR structures.',/info
      (spchdr.ftflgs AND 32) gt 0: message,'Axis label text stored in fcatxt separated by nulls. Ignore fxtype, fytype, fztype corresponding to non-null text in fcatxt.',/info
      (spchdr.ftflgs AND 64) gt 0: message,'Each subfile has unique X array; can only be used if TXVALS is also used. Used exclusively to flag as MS data for drawing as �sticks� rather than connected lines.',/info
      (spchdr.ftflgs AND 128) gt 0: message,'Non-evenly spaced X data. File has X value array preceding Y data block(s).',/info
      else:
    endcase
  endif

  comment=string(spchdr.fcmnt)
  xstart=spchdr.ffirst
  xinc=(spchdr.flast-spchdr.ffirst)/(spchdr.fnpts-1)

  if (spchdr.ftflgs AND '80'xb) gt 0 then begin			;uneven spaced x-data included in file
    freq=fltarr(spchdr.fnpts)
    readu,lun,freq
  endif else begin		;file is regularly spaced. no x-data stored in file
    freq=findgen(spchdr.fnpts)*xinc+xstart
  endelse

  XUNITS=SPCHDR.fxyztype[0]

  case xunits of
    0: xunit_text='Arbitrary Units'
    1: xunit_text='Wavenumber (cm-1)'
    2: xunit_text='Wavelength (um)'
    3: xunit_text='Wavelength (nm)'
    4: xunit_text='Time (s)'
    5: xunit_text='Time (m)'
    6: xunit_text='Frequency (Hz)'
    7: xunit_text='Frequency (KHz)'
    8: xunit_text='Frequency (MHz)'
    9: xunit_text='Mass (M/z)'
    10: xunit_text='PPM'
    11: xunit_text='Time (d)'
    12: xunit_text='Time (yr)'
    13: xunit_text='Raman Shift (cm-1)'
    14: xunit_text='Energy (eV)'
    15: ; X,Y,Z text labels in fcatxt (old 4Dh version only)
    16: xunit_text='Diode Number'
    17: xunit_text='Channel'
    18: xunit_text='Degrees'
    19: xunit_text='Temperature (F)'
    20: xunit_text='Temperature (C)'
    21: xunit_text='Temperature (K)'
    22: xunit_text='Data Points'
    23: xunit_text='Time (mSec)'
    24: xunit_text='Time (uSec)'
    25: xunit_text='Time (nSec)'
    26: xunit_text='Frequency (GHz)'
    27: xunit_text='Wavelength (cm)'
    28: xunit_text='Wavelength (m)'
    29: xunit_text='Wavelength (mm)'
    30: xunit_text='Time (hr)'
    255: xunit_text='Interferogram Sample'   ;Double interferogram, no display labels.
    else: xunit_text=''
  endcase

  YUNITS=SPCHDR.fxyztype[1]

  case yunits of
    0: yunit_text='Arbitrary Intensity'
    1: yunit_text='Interferogram'
    2: yunit_text='Absorbance'
    3: yunit_text='Kubelka-Munk'
    4: yunit_text='Counts'
    5: yunit_text='Volts'
    6: yunit_text='Degrees'
    7: yunit_text='Milliamps'
    8: yunit_text='Millimeters'
    9: yunit_text='Millivolts'
    10: yunit_text='Log (1/R)'
    11: yunit_text='Percent'
    12: yunit_text='Intensity'
    13: yunit_text='Relative Intensity'
    14: yunit_text='Energy'
    15: yunit_text=''
    16: yunit_text='Decibel'
    17: yunit_text=''
    18: yunit_text=''
    19: yunit_text='Temperature (F)'
    20: yunit_text='Temperature (C)'
    21: yunit_text='Temperature (K)'
    22: yunit_text='Index of Refraction [N]'
    23: yunit_text='Extinction Coeff. [K]'
    24: yunit_text='Real'
    25: yunit_text='Imaginary'
    26: yunit_text='Complex'
    128: yunit_text='Transmission'; (ALL TYPES >=128 ARE ASSUMED TO HAVE INVERTED PEAKS!)
    129: yunit_text='Reflectance'
    130: yunit_text='Arbitrary or Single Beam with Valley Peaks'
    131: yunit_text='Emission'
    else: yunit_text=''
  endcase

  ZUNITS=SPCHDR.fxyztype[2]
  case zunits of
    0: zunit_text='Arbitrary Units'
    1: zunit_text='Wavenumber (cm-1)'
    2: zunit_text='Wavelength (um)'
    3: zunit_text='Wavelength (nm)'
    4: zunit_text='Time (s)'
    5: zunit_text='Time (m)'
    6: zunit_text='Frequency (Hz)'
    7: zunit_text='Frequency (KHz)'
    8: zunit_text='Frequency (MHz)'
    9: zunit_text='Mass (M/z)'
    10: zunit_text='PPM'
    11: zunit_text='Time (d)'
    12: zunit_text='Time (yr)'
    13: zunit_text='Raman Shift (cm-1)'
    14: zunit_text='Energy (eV)'
    15: ; X,Y,Z text labels in fcatxt (old 4Dh version only)
    16: zunit_text='Diode Number'
    17: zunit_text='Channel'
    18: zunit_text='Degrees'
    19: zunit_text='Temperature (F)'
    20: zunit_text='Temperature (C)'
    21: zunit_text='Temperature (K)'
    22: zunit_text='Data Points'
    23: zunit_text='Time (mSec)'
    24: zunit_text='Time (uSec)'
    25: zunit_text='Time (nSec)'
    26: zunit_text='Frequency (GHz)'
    27: zunit_text='Wavelength (cm)'
    28: zunit_text='Wavelength (m)'
    29: zunit_text='Wavelength (mm)'
    30: zunit_text='Time (hr)'
    255: zunit_text='Interferogram Sample'   ;Double interferogram, no display labels.
    else: zunit_text=''
  endcase

  if (SPCHDR.ftflgs AND '20'xb) gt 0 then begin	;custom axis text overides
    str=string(SPCHDR.fcatxt)
    ind=0
    if str ne '' then xunit_text = str
    ind+=strlen(str)+1
    str=string(spchdr.fcatxt[ind:*])
    if str ne '' then yunit_text = str
    ind+=strlen(str)+1
    str=string(spchdr.fcatxt[ind:*])
    if str ne '' then zunit_text = str
  endif

  zdata=fltarr(SPCHDR.fnsub)

  ydata=fltarr(spchdr.fnpts,SPCHDR.fnsub)

  for i=0L,SPCHDR.fnsub-1 do begin

    readu,lun,SUBHDR
    zdata[SUBHDR.subindx]=SUBHDR.subtime

    subexp=fix(subhdr.subexp)   ;this works for non-IEE format

    if fexp ne 128 then begin				;not IEEE format. do conversion
      message,'Non-IEEE 32bit format,  fexp='+string(fexp),/continue
      yldata=lonarr(spchdr.fnpts)
      readu,lun,yldata
      if fexp gt 120 then message,'fexp is too large',/continue  else $
        ydata[*,i]=float(2d^subexp*yldata/(2d^32))
    endif else begin		;IEEE floating point format
      Y=fltarr(spchdr.fnpts)
      readu,lun,Y
      ydata[*,i]=Y
    endelse

  endfor

  ydata=reform(ydata)	;get rid of extra dimensions

  if SPCHDR.flogoff ne 0 then begin
    ;64 bytes + info blocks
    LOGSTC={logsizd:long(0),$		;64 + size of header
      logsizm:long(0),$			;multiple of 4096, bigger than logsizd
      logtxto:long(0),$			;?
      logbins:long(0),$	; binary block data size
      logdsks:long(0),$	; secondary binary block data size
      logspar:bytarr(44) $
    }

    readu,lun,LOGSTC
    if arg_present(header) then begin
      ;read in the info block appropriate for the type of file:
      case logstc.logbins of
        0: begin  ;no header
          message,'NO HEADER/INFO BLOCKS IN '+filename+' !',/info
        end
        2048 : begin ;old style file
          info1=lonarr(256)	;old style infoblocks
          info2=info1
          readu,lun,info1,info2
        end
        904 : begin	;old MZ FTS file
          message,'This file contains old (pre 12/01) MZ info blocks, which were NOT read.',/info
          ;				readu,lun,info
          ;				info1=info
          ;				info2=info
        end
        936 : begin ;n_tags({mz_infoblock},/data_length) : begin	;current version (1.0) rapid scan MZ FTS file
          info={mz_infoblock} ;MZ fts infoblock structure. be aware that this structure can change. check the version number
          readu,lun,info
          info1=info
          info2=info
          header=info
        end
        944: begin ;n_tags({mz_infoblock_v2},/data_length) : begin		;version 2.0 (step and integrate)
          info={mz_infoblock_v2}
          readu,lun,info
          info1=info
          info2=info
          header=info
        end
        256: begin	;n_tags({mpi_fts_header},/data_length) : begin		;MPI FTS header
          header={mpi_fts_header}
          readu,lun,header
        end
        247: begin	;SOLOIST_FTS file header
          header={soloist_fts_header}
          readu,lun,header
        end
        408: begin	; BTRAM SPC file header
          header={btram_file_header}
          readu,lun,header
        end
        359: begin  ;SOLOIST_FTS file header
          header={rrcat_soloist_fts_header}
          readu,lun,header
        end
        SPCHDR.fnsub*96: begin  ; ITER FTS header data (May need to be modified)
          header=replicate({ITER_SPC_HEADER},SPCHDR.fnsub)
          readu,lun,header
        end

        else : begin;unexpected header size. Read to end of file and return in header.
          message, name='read_spc_bad_header', block='read_spc', strtrim(logstc.logbins,2),/continue

          err=-2
          point_lun,-lun,pos
          remaining =(file_info(filename)).size - pos
          header=bytarr(logstc.logbins < remaining)
          readu,lun,header
        endelse
      endcase
    endif

  endif else begin	;no header info in file.
    if (arg_present(info1) or arg_present(info2) or arg_present(info) or arg_present(header)) then begin
      message,'NO HEADER/INFO BLOCKS IN '+filename+' !',/info
    endif
  endelse

  fres=string(spchdr.fres)
  fsource=string(spchdr.fsource)
  fcatxt=string(spchdr.fcatxt)

  free_lun,lun
  return
end
